server.port=8080

# Use this pattern to show reduced log width
logging.pattern.console= %d{HH:mm:ss} [%15thread] %msg%n

logging.level.web=TRACE
logging.level.org.springframework.web.client=TRACE

# KeyCloak specific OAuth 2 related properties
spring.security.oauth2.client.registration.keycloak-oidc.provider=keycloak
spring.security.oauth2.client.registration.keycloak-oidc.client-name=Keycloak
spring.security.oauth2.client.registration.keycloak-oidc.client-id=bugtracker
spring.security.oauth2.client.registration.keycloak-oidc.client-secret=<<Enter Secret>>
spring.security.oauth2.client.registration.keycloak-oidc.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak-oidc.scope=openid,profile,email

# You need to set the issuer correctly
# Openid configuration - http://127.0.0.1:9090/realms/oauthrealm/.well-known/openid-configuration
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://127.0.0.1:9090/realms/oauthrealm

# GitLab specific OAuth 2 related properties
spring.security.oauth2.client.registration.gitlab-oidc.provider=gitlab
spring.security.oauth2.client.registration.gitlab-oidc.client-name=GitLab
spring.security.oauth2.client.registration.gitlab-oidc.client-id=39bae329d9896c6cb6edb69d7aaa9c3c2185e67f07d565e7392ffb3153b086c2
spring.security.oauth2.client.registration.gitlab-oidc.client-secret=gloas-3c9c7466027fd8986fdc8db05c8f220ebb6a9a91dbcbca3bf16d2983f487b818
spring.security.oauth2.client.registration.gitlab-oidc.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gitlab-oidc.scope=openid,profile,email

# You need to set the issuer correctly (Not Strictly Required because its already known to Spring Boot)
# Openid configuration - https://gitlab.com/.well-known/openid-configuration
spring.security.oauth2.client.provider.gitlab.issuer-uri=https://gitlab.com